### ISSUE TITLE
Organization for single problems better divided into multiple files

### ISSUE THREAD

**Issue by skylermishkin** [skylermishkin/algorithmic-heights#5]
Getting to the degree array (deg) problem in algorithmic heights, it sure seems that an UndirectedGraph class is something to use... and something that will likely have future utility. Where do you think we should put extra utility files (holding code that does not uniquely solve the specified problem)? Seem standard/reasonable for these to go into a util directory at the top level (with the readme, src/, and scripts/)? or maybe just in src/util/?

**Comment by mondomishi** [comment]
My immediate reaction is to _not_ encourage the sharing of files between different problem solutions.  Here's why:

Suppose problem `A` defines some function `util/f` and uses it to solve the problem.  Then later, we come across problem `B` in which `f` is close to, but not quite what we want.  Thus we fix up `f`, use it to solve `B`, and now `B` is solved.  But we have broken the solution to `A` since we have modified `f`.

At the moment, it seems to me that it would be easier to simply copy over a file `A/f` into `B` if you wanted to use it in `B`.  Thus each problem's directory is self contained and the solutions to old problems can't be broken by solving new problems.

Certainly open to hearing other ideas though.

**Comment by skylermishkin** [comment]
I think that is fair justification for custom helpers. The only reasonable disagreement would need to include standard procedure as testing all shared file dependents each mod... sounds like more hassle than it's worth, and generally for the development & debug processes required to maintain functional clarity. Another little cherry is writing a custom (streamlined) variant of a class each implementation could enhance performance/memory.
